### ISSUE TITLE
Code for RobotServer

### ISSUE THREAD

**Issue by mstoelzle** [anoff/ric#8]
Hi,

I am interested in the code you used as part of the RobotServer to communicate via LAN with the Festo motion terminal. Would you mind uploading this part?

**Comment by anoff** [comment]
Hey Maximilian,

sorry for the late response.
As this project was part of a company backed hackathon we were actually working with systems partially provided by Festo. The RobotServer was such a thing. iirc it was a kind of RnD implementation by a PhD student.

I can give you the Name + Mail of one of the Festo guys that was there if you want to see if they are open to sharing :)

**Comment by mstoelzle** [comment]
Hi Andreas,

Thanks for your response. I have figured out the communication from ROS now. But it was a bit of a painful experience because of the lack of good documentation :/

We have open-sourced the ROS package:
https://github.com/tud-cor-sr/ros2-vtem_control

Thanks for your offer and help :)
